# Generated by Django 5.2.16 on 2026-07-17 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resettlementfollowup',
            name='resettlement',
        ),
        migrations.CreateModel(
            name='CivilCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incomplete_data_flag', models.BooleanField(default=False)),
                ('missing_fields', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('court_name_location', models.CharField(blank=True, max_length=200)),
                ('application_category', models.CharField(blank=True, choices=[('custody', 'Custody'), ('maintenance', 'Maintenance'), ('guardianship', 'Guardianship'), ('adoption', 'Adoption'), ('declaration_of_parentage', 'Declaration of Parentage'), ('care_order', 'Care Order'), ('supervision_order', 'Supervision Order'), ('interim_order', 'Interim Care or Supervision Order'), ('exclusion_order', 'Exclusion Order'), ('emergency_protection_order', 'Emergency Protection Order'), ('search_production_order', 'Search and Production Order'), ('recovery_order', 'Recovery Order'), ('appeal', 'Appeal')], max_length=30)),
                ('case_file_number', models.CharField(blank=True, max_length=120)),
                ('presiding_officer', models.CharField(blank=True, max_length=160)),
                ('applicant_details', models.TextField(blank=True)),
                ('respondent_details', models.TextField(blank=True)),
                ('background_reason', models.TextField(blank=True)),
                ('court_decision_order', models.TextField(blank=True)),
                ('compliance_requirements', models.TextField(blank=True)),
                ('responsible_persons', models.CharField(blank=True, max_length=200)),
                ('coordinator_comments', models.TextField(blank=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='civil_cases', to='cases.case')),
                ('supporting_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='civil_case_docs', to='cases.document')),
            ],
            options={
                'verbose_name': 'Civil Case',
                'verbose_name_plural': 'Civil Cases',
            },
        ),
        migrations.CreateModel(
            name='CivilCaseHearing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hearing_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('civil_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearings', to='cases.civilcase')),
            ],
            options={
                'verbose_name': 'Civil Case Hearing',
            },
        ),
        migrations.CreateModel(
            name='Counselling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incomplete_data_flag', models.BooleanField(default=False)),
                ('missing_fields', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_datetime', models.DateTimeField(blank=True, null=True)),
                ('session_type', models.CharField(blank=True, choices=[('individual', 'Individual'), ('group', 'Group'), ('family', 'Family'), ('psychosocial', 'Psychosocial Support')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('duration', models.CharField(blank=True, max_length=60)),
                ('counsellor_role', models.CharField(blank=True, choices=[('j4c_coordinator', 'J4C Coordinator'), ('external_professional', 'External Professional')], max_length=25)),
                ('professional_full_name', models.CharField(blank=True, max_length=160)),
                ('reason', models.TextField(blank=True, help_text='Trauma, Abuse, Behavioural Challenges, Reintegration, Diversion, Family Conflict, Court-ordered, etc.')),
                ('other_reason_details', models.TextField(blank=True)),
                ('observations_assessment', models.TextField(blank=True)),
                ('interventions_provided', models.TextField(blank=True)),
                ('emotional_status_post', models.TextField(blank=True)),
                ('recommendations_referrals', models.TextField(blank=True, help_text='Legal Aid, Medical Examination, Psychiatric Referral, Educational Support, etc.')),
                ('referral_details', models.TextField(blank=True)),
                ('next_session_datetime', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counselling_sessions', to='cases.case')),
                ('supporting_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counselling_docs', to='cases.document')),
            ],
            options={
                'verbose_name': 'Counselling Session',
                'verbose_name_plural': 'Counselling Sessions',
            },
        ),
        migrations.DeleteModel(
            name='Resettlement',
        ),
        migrations.DeleteModel(
            name='ResettlementFollowUp',
        ),
    ]
